---
abstract: 'Safe user and group ID variables'
author:
  - 'Leon Timmermans <leont@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  POSIX: 0
  Test::Exception: 0
  Test::More: 0
  if: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: autodie-variables
requires:
  XSLoader: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=autodie-variables
  repository: git://github.com/Leont/autodie-variables.git
version: 0.005
